[package]
name = "ray_tracing_in_one_we"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23"
rayon = "1.6"
nalgebra-glm = "0.17"
once_cell = "1.16"
