[package]
name = "ray_tracing_in_one_we"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.20.0"
rayon = "1.5.1"
nalgebra-glm = "0.15.0"